# Generated by Django 5.0.2 on 2024-03-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_shipment_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
