# Generated by Django 5.0.2 on 2024-03-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_vehicle_driver_mobile_vehicle_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(default='available', max_length=50),
        ),
    ]
